// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {RoleManager} from "../access/RoleManager.sol";

/**
 * @title ProductBatch
 * @dev Stores product hashes and ownership on-chain.
 *      Full product metadata lives in MongoDB.
 *      Blockchain stores: hash, creator, timestamp, current owner.
 *
 *  Transfer rules (enforced on-chain):
 *    MANUFACTURER → SUPPLIER ✅
 *    SUPPLIER     → WAREHOUSE ✅
 *    WAREHOUSE    → RETAILER ✅
 *    All others   → ❌ reverts
 */
contract ProductBatch {

    // ── State ──────────────────────────────────────────────────────────────

    RoleManager public roleManager;

    struct Product {
        bytes32 productHash;   // SHA256 of MongoDB metadata
        address creator;       // manufacturer wallet
        uint256 timestamp;     // block time of creation
        string  batchId;       // human-readable batch identifier
        address currentOwner;  // current custodian
        bool    exists;
    }

    // productHash → Product
    mapping(bytes32 => Product) public products;

    // batchId string → productHash (for easy lookup)
    mapping(string => bytes32) public batchIdToHash;

    // manufacturer wallet → list of their product hashes
    mapping(address => bytes32[]) public manufacturerProducts;

    // ── Events ─────────────────────────────────────────────────────────────

    event ProductCreated(
        bytes32 indexed productHash,
        address indexed creator,
        string  batchId,
        uint256 timestamp
    );

    event OwnershipTransferred(
        bytes32 indexed productHash,
        address indexed from,
        address indexed to,
        uint256 timestamp
    );

    // ── Modifiers ──────────────────────────────────────────────────────────

    modifier onlyManufacturer() {
        require(
            roleManager.getRole(msg.sender) == RoleManager.Role.MANUFACTURER,
            "Only Manufacturer"
        );
        _;
    }

    modifier productExists(bytes32 _productHash) {
        require(products[_productHash].exists, "Product not found");
        _;
    }

    // ── Constructor ────────────────────────────────────────────────────────

    constructor(address _roleManager) {
        roleManager = RoleManager(_roleManager);
    }

    // ── Functions ──────────────────────────────────────────────────────────

    /**
     * @notice Manufacturer registers a product batch on-chain.
     * @param _productHash SHA256 hash generated by backend from MongoDB data
     * @param _batchId     Human-readable batch ID (must be unique)
     */
    function createProduct(
        bytes32 _productHash,
        string memory _batchId
    ) external onlyManufacturer {
        require(!products[_productHash].exists, "Hash already exists");
        require(batchIdToHash[_batchId] == bytes32(0), "Batch ID already exists");
        require(bytes(_batchId).length > 0, "Batch ID cannot be empty");

        products[_productHash] = Product({
            productHash:  _productHash,
            creator:      msg.sender,
            timestamp:    block.timestamp,
            batchId:      _batchId,
            currentOwner: msg.sender,
            exists:       true
        });

        batchIdToHash[_batchId] = _productHash;
        manufacturerProducts[msg.sender].push(_productHash);

        emit ProductCreated(_productHash, msg.sender, _batchId, block.timestamp);
    }

    /**
     * @notice Transfer product ownership following supply chain rules.
     * @param _productHash Hash of the product to transfer
     * @param _to          Wallet address of the recipient
     */
    function transferProduct(
        bytes32 _productHash,
        address _to
    ) external productExists(_productHash) {

        Product storage product = products[_productHash];

        require(product.currentOwner == msg.sender, "Not the current owner");
        require(_to != address(0), "Invalid recipient");

        RoleManager.Role fromRole = roleManager.getRole(msg.sender);
        RoleManager.Role toRole   = roleManager.getRole(_to);

        require(_isValidTransfer(fromRole, toRole), "Invalid transfer path");

        address previousOwner = product.currentOwner;
        product.currentOwner  = _to;

        emit OwnershipTransferred(_productHash, previousOwner, _to, block.timestamp);
    }

    /// @notice Get full product details by hash
    function getProduct(bytes32 _productHash)
        external
        view
        returns (Product memory)
    {
        return products[_productHash];
    }

    /// @notice Get product details by batch ID string
    function getProductByBatchId(string memory _batchId)
        external
        view
        returns (Product memory)
    {
        bytes32 hash = batchIdToHash[_batchId];
        return products[hash];
    }

    /// @notice Get all product hashes created by a manufacturer
    function getManufacturerProducts(address _manufacturer)
        external
        view
        returns (bytes32[] memory)
    {
        return manufacturerProducts[_manufacturer];
    }

    // ── Internal ───────────────────────────────────────────────────────────

    /// @dev Validates the transfer direction in the supply chain
    function _isValidTransfer(
        RoleManager.Role from,
        RoleManager.Role to
    ) internal pure returns (bool) {
        if (from == RoleManager.Role.MANUFACTURER && to == RoleManager.Role.SUPPLIER)  return true;
        if (from == RoleManager.Role.SUPPLIER     && to == RoleManager.Role.WAREHOUSE) return true;
        if (from == RoleManager.Role.WAREHOUSE    && to == RoleManager.Role.RETAILER)  return true;
        return false;
    }
}
